### ISSUE TITLE
Unit health/action bars are displaced on screen resize

### ISSUE THREAD

**Issue by Lordbob** [Byteron/haldric-next#54]
While running the game, if I enlarge the main window, status bars become disconnected from their owner.

![image](https://user-images.githubusercontent.com/4284022/139602659-15bebc05-279f-4d52-83be-5131447925cf.png)

**Comment by Byteron** [comment]
I am 99% sure this is an engine bug that we can't do much about right now.
I disabled resizing window for now, so this can't happen. Not ideal but this is something to deal with later when we start thinking about actually giving this into players hands.
