### ISSUE TITLE
Cliffs

### ISSUE THREAD

**Issue by Lordbob** [Byteron/haldric-next#89]
Replace the placeholder prop with a decent textured model

**Comment by Byteron** [comment]
Also massively reduce poly count since the current props massively tank FPS.

**Comment by Lordbob** [comment]
We're almsot there. All that remains is to add support for texture variation between different terrain types (grass cliff, sand cliff, ...)

**Comment by Lordbob** [comment]
Done. Cliff types now include variants with grass, dirt, sand, and bare rock depending on the type of terrain at the top.
It will be possible to add terrain specific cliff meshes and/or new texture variants in the future.
